bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users do
  resource :relationships, only: [:create, :destroy] 
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :following, :followers
    end  
end
  
  
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

   
end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true

end


  

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates :book, uniqueness: true
   
end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
   
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  #has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  #has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  #has_many :following_user, through: :follower, source: :followed
  #has_many :follower_user, through: :followed, source: :follower
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  attachment :profile_image
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end  
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])  
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id 
    if @book.save
      flash[:notice] = 'successfully'
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end  
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end 

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new = Book.new
    @book_comment = BookComment.new
  end
  
  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end  
  end 
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'successfully'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end 
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end  
end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

def create
  book = Book.find(params[:book_id])
  favorite = current_user.favorites.new(book_id: book.id)
  favorite.save
  # redirect_to book_path(book)
  redirect_back(fallback_location: root_path)
end

def destroy
  book = Book.find(params[:book_id])
  favorite = current_user.favorites.find_by(book_id: book.id)
  favorite.destroy
  # redirect_to book_path(book)
  redirect_back(fallback_location: root_path)
end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
  
end

bookers2/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

def create
  current_user.follow(params[:user_id])
  redirect_to request.referer
end
  
def destroy
  current_user.unfollow(params[:user_id])
  redirect_to request.referer
end

def followings
  user = User.find(params[:user_id])
  @users = user.followings  
end  

def followers
  user = User.find(params[:user_id])
  @users = user.followers
end
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book
  end  
  
  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end  
  end  
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'successfully'
      redirect_to user_path(@user)
    else
      render :edit
    end  
  end
  
    private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end  
end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/_list.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <table class="table">
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>  
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
    <tr>
      <td>follows</td>
      <td><%= link_to user.followings.count, user_followings_path(user) %></td>
    </tr>  
    <tr>
      <td>followers</td>
      <td><%= link_to user.followers.count, user_followers_path(user) %></td>  
    </tr>
    
  </table>
       
  <%= link_to "", edit_user_path(user),class:"btn btn-secondary btn-block fas fa-user-cog edit_user_id" %>
        
<h2>New book</h2>
<%= form_with model:book, url:'/books', local:true do |f| %>

<h4>title</h4>
<%= f.text_field :title %>

<h4>body</h4>
<%= f.text_area :body %>

<br><%= f.submit 'Create Book', class: "btn btn-success btn-sm" %>

<% end %>    

bookers2/app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>   

<div class="container">
  <div class="row">
    <div class="mx-auto">  
      <h1>Editing Book</h1>
      <%= form_with model:@book, url:"/books/#{@book.id}", local: true do |f| %>

      <h4>title</h4>
      <%= f.text_field :title %>

      <h4>body</h4>
      <%= f.text_area :body %>

      <br><%= f.submit 'Update Book', class: "btn btn-success btn-sm" %>

      <% end %> 

      <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
      <!--<a class="book_id" href="/books/id">Show</a> | <a class="books" href="/books"></a>-->
    </div>
  </div>
</div>  

bookers2/app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>  

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "books/list",book:@book,user:@user %>
    </div>
      
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
          
            <table class="table">
              <thead>
                <tr>
                  <td></td>
                  <td>title</td>
                  <td>body</td>
                </tr>
              </thead>
          
          　 　<tbody>
          　 　 <% @books.each do |book| %> 
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
                  </td>
                    <% end %>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                  <td>
                    <% if book.favorited_by?(current_user) %>
                      <p>
                        <%= link_to book_favorites_path(book), method: :delete do %>
                          ♥<%= book.favorites.count %>
                    <% end %>
                      </p>
                        <% else %>
                      <p>
                        <%= link_to book_favorites_path(book), method: :post do %>
                          ♡<%= book.favorites.count %>
                        <% end %>
                      </p>
                      <% end %>        
                  </td>
                  <td><p><%= link_to "コメント数#{book.book_comments.count} ", book_path(book.id) %></p>
                </tr>
                <% end %> 
              </tbody> 
            </table>
      </div>
  </div>
</div>

bookers2/app/views/books/new.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <img class="attachment user profile_image fallback" src="no_image.jpg">
        <table>
          <tr>
            <td>name</td>
          </tr>  
          <tr>
            <td>introduction</td>
          </tr>    
        </table>
        <div class="row">
          <a class="btn btn-secondary rtn-block fas fa-user-cog edit_user_id" ></a>    
        </div>
      </div>    
    </div>
  </div>    
</main>

<h1>New Book</h1>
<%= form_with model:@book, url:'/books', local:true do |f| %>

  <h4>title</h4>
  <%= f.text_field :title %>

   <h4>body</h4>
  <%= f.text_area :body %>

  <br><%= f.submit 'Create Book' %></>

<% end %>

bookers2/app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "books/list",book:@new,user:@user %>
    </div>
          
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>      
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@book.user) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
                  <div><%= @book.user.name %></div>
                  <% end %>
                </td>  
                <td><%= link_to @book.title %></td>
                <td><%= @book.body %></td>
                <td>
                  <% if @book.favorited_by?(current_user) %>
                    <p>
                      <%= link_to book_favorites_path(@book), method: :delete do %>
                        ♥<%= @book.favorites.count %>
                      <% end %>
                    </p>
                      <% else %>
                    <p>
                      <%= link_to book_favorites_path(@book), method: :post do %>
                        ♡<%= @book.favorites.count %>
                      <% end %>
                    </p>
                  <% end %>    
                </td>    
                <td><p>コメント数：<%= @book.book_comments.count %></p></td>
                  <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success btn-sm" %></td>
                <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-danger btn-sm" %></td>
                  <% end %>
              </tr>
        
              <div class="comments">
                <% @book.book_comments.each do |book_comment| %>
                  <tr>
                    <td><p><%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></p>
                    <td><%= book_comment.user.name %></td>
                      <% if book_comment.user == current_user %>
              <div class="comment-delete">
                <td>
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn btn-danger btn-sm" %>
                </td>
                  </tr>
              </div>
                <% end %>
                      <% end %>
              </div>
            </tbody>  
          </table>
  
              <div class="new-comment">
                <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
                <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
                <br><%= f.submit "送信" %>
                <% end %>
              </div>
      </div>
  </div>  
</div>
          
          
  
          





  

bookers2/app/views/homes/about.html.erb
<main>
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>welcome to 
        <i class="fas fa-book"></i>Bookers !!
      </h1>
    </div>
  </div>
</div>
</main>

bookers2/app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>welcome to 
        <i class="fas fa-book"></i>Bookers !!
      </h1>
      <p>In
        <i class="fas fa-book"></i>Bookers ,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotion</P>
      <P>about various books!</P>
      
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">  
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block" %>
        </div>
        <br><div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>  
      </div>
    </div>
  </div>    
</div>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/fb53ccb37d.js" crossorigin="anonymous"></script>
    
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <a class="navbar-brand" href="/">
          <span>Bookers</span>
        </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span claas="navbar-toggler-icon"></span> 
          </button>
      
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <!--<a class="fas fa-home nav-link text-light" href="/users"><--></-->
                <!--Home-->
              <%= link_to "Home", user_path(current_user), class: "fas fa-home nav-link text-light" %>
            </li>
            <li>
              <a class="fas fa-users nav-link text-light" href="/users">
                Users
              </a>
            </li>
            <li>
              <a class="fas fa-book-open nav-link text-light" href="/books">
                Books
              </a>  
            </li>
            <li>
              <a class="fas fa-sign-out-alt nav-link text-light" data-method="delete" href="/users/sign_out">
                Logout
              </a>
            </li>　
            <% else %>
            <li>
              <a class="fas fa-home nav-link text-light" href="/">
                Home
              </a>
            </li>
            <li>
              <a class="fas fa-link nav-link text-light" href="/home/about">
                About
              </a>
            </li>
            <li>
              <a class="fas fa-user-plus nav-link text-light" href="/users/sign_up">
                sign up
              </a>  
            </li>
            <li>
              <a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in">
                login
              </a>
            </li>
            <% end %>
            </ul>
          </div> 
        </div> 
      </nav>
    </header>
   
    <main>
    <%= flash[:notice] %> 
    <%= yield %>
    </main>
 
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p> CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

bookers2/app/views/relationships/followers.html.erb
<h1>Followers Users</h1>
<% if @users.exists? %>
  <table table="class" width="100%">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to "Show", ccurrent_user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

bookers2/app/views/relationships/followings.html.erb
<h1>Follow Users</h1>
<% if @users.exists? %>
  <table table="class" width="100%">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to "Show", current_user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

bookers2/app/views/users/_list.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <table class="table"> 
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>  
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
    <tr>
      <td>follows</td>
      <td><%= link_to user.followings.count, user_followings_path(user) %></td>
    </tr>  
    <tr>
      <td>followers</td>
      <td><%= link_to user.followers.count, user_followers_path(user) %></td>  
    </tr>
      <td>
        <% if user_signed_in? && current_user != @user %>
        <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info btn-block btn-sm" %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success btn-block btn-sm" %>
        <% end %>
        <% end %>
      </td>  
  </table>
     
  <%= link_to "", edit_user_path(user),class: "btn btn-secondary btn-block fas fa-user-cog edit_user_id" %>
    
<h2>New book</h2>
<%= form_with model: book, url:'/books', local: true do |f| %>

<h4>title</h4>
<%= f.text_field :title %>

<h4>body</h4>
<%= f.text_area :body %>

<br><%= f.submit 'Create Book', class: "btn btn-success btn-sm" %>

<% end %>
 

bookers2/app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %> 

<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>User info</h1>
        <%= form_with model:@user, local:true do |f| %>
          <label for="inputName">Name</label>
         
          <h4>Name</h4>
          <%= f.text_field :name %>
    
          <h4>Image</h4>
          <%= f.attachment_field :profile_image %>
    
          <h4>Introduction</h4>
          <%= f.text_area :introduction %>
    
          <br><%= f.submit "Update User" %> 
  
        <% end %>
    </div>
  </div>
</div>  

bookers2/app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "books/list",book:@book,user:@user %>
  　</div>
    
      <div class="col-md-8 offset-md-1">
        <h1>Users</h1>
          
            <table class="table">
              <thead>
                <tr>
                  <th>image</th>
                  <th>name</th>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>  
              </thead>
        
              <tbody>
                <% @users.each do |user| %>
                <tr>
                  <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%></td>
                  <td><span><%= user.name %></span></td>
                  <td>フォロー数: <%= user.followings.count %></td>
                  <td>フォロワー数: <%= user.followers.count %></td>
                  <td>
                    <% if current_user.following?(user) %>
                      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                    <% else %>
                      <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                    <% end %>
                  </td>
                  <td><%= link_to "Show", user_path(user.id) %></td>
                </tr>  
          <% end %>
              </tbody>
            </table>
      </div>
  </div>
</div>

bookers2/app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/list",book:@book,user:@user %>
　　</div>
   
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
          <% @books.each do |book| %>
            <table class="table">
              <thead>
                <tr>
                  <th></th>
                  <th>title</th>
                  <th>body</th>
                </tr>
              </thead>
        
              <tbody>
                <tr>
                  <!--<td></td>-->
                  <td>
                    <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
                    <% end %> 
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                </tr>
              </tbody>    
            </table>
          <% end %>
      </div>
  </div>
</div>  